system("pwd")
setwd("/home/radivot/GH/protein-folding-qc/res/tom/amber/FCC5") 
system("pwd")
Sys.setenv(AMBERHOME= "/home/radivot/soft/amber22")
system("echo $AMBERHOME")
system("echo $PATH")
system("$AMBERHOME/bin/tleap -s -f leapF5.in > leapF5.out")
system("mpirun -np 12 $AMBERHOME/bin/sander.MPI -O -i min1.in -o min1.out.FAIL_sander -p TC5b.prmtop -c TC5b.rst7 -r min1.ncrst")
system("mpirun -np 12 $AMBERHOME/bin/pmemd.MPI -O -i min1.in -o min1.out.FAIL_pme -p TC5b.prmtop -c TC5b.rst7 -r min1.ncrst")
